# SPARQL 1.1
# Data: figure10g.n4
# Documentation: https://www.w3.org/TR/sparql11-query/
# Source code: https://github.com/nunolopes/anql

PREFIX : <http://example.org/>

SELECT ?city {
  :Santiago :flight ?city .
  ?event :city ?city .
}
