# SPARQL
# Data: figure1.ttl
# Ontology: figure13-ontology.ttl
# Documentation: https://www.w3.org/TR/sparql11-query/
# Try online: https://rdfshape.weso.es/
# Try online: http://rdfplayground.dcc.uchile.cl/

PREFIX : <http://example.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?name {
  ?festival rdf:type  :Festival ;
            :location :Santiago ;
            :name     ?name .
}
