# SPARQL 1.1
# Data: figure1.ttl
# Documentation: https://www.w3.org/TR/sparql11-query/
# Try online: https://rdfshape.weso.es/
# Try online: http://sparql-playground.sib.swiss/
# Try online: http://rdfplayground.dcc.uchile.cl/

PREFIX : <http://example.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?event ?name ?city {
  ?event :name    ?name ;
         rdf:type :FoodFestival .
  :Arica (:bus|:flight)* ?city .
  ?city ^(:venue/:city) ?event .
}
